### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by vflorin1995** [laiifuu/To-Do-List#4]
Hello Hayet! Your code looks amazing, but it can be a little improved. Please check the following issues!
![image](https://user-images.githubusercontent.com/108400762/193216145-b939f46e-1ccb-43bc-b2d5-875fa2c8cc58.png)

Issues:
- Empty list items can be inserted into your list
- If a task is edited and is left empty, the task will not delete itself

**Comment by laiifuu** [comment]
Thank you, these issues have been fixed  :smile:
